redis/redis-om-spring

redis-om-spring/src/main/java/com/redis/om/spring/RedisModulesConfiguration.java
- This lead to errors when application contexts changed, which did not have the `SpringBootApplication` class
=> fix: adds null check to bean fetching in RedisModulesConfiguration

redis-om-spring/src/main/java/com/redis/om/spring/metamodel/indexed/TagField.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/SearchStreamImpl.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/actions/ArrayAppendAction.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/actions/ArrayIndexOfAction.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/actions/ArrayInsertAction.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/actions/ArrayLengthAction.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/actions/ArrayPopAction.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/actions/ArrayTrimAction.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/actions/NumIncrByAction.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/actions/StrLengthAction.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/actions/StringAppendAction.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/actions/TakesJSONOperations.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/actions/ToggleAction.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/User.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/UserRepository.java, redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamTest.java
Implements JSON.ARR* methods as terminal operations on Entity Streams, for example:
Entity Stream on a `Company` entity with a `tags` Set field, below we find the company "Microsoft" and add the String "gaming" to the Set of tags.
```
@Test
public void testArrayAppendToSimpleIndexedTagFieldInDocuments() {
entityStream.of(Company.class) //
.filter(Company$.NAME.eq("Microsoft")) //
.forEach(Company$.TAGS.add("gaming"));
Optional<Company> maybeMicrosoft = repository.findFirstByEmail("research@microsoft.com");
assertTrue(maybeMicrosoft.isPresent());
Company microsoft = maybeMicrosoft.get();
assertThat(microsoft.getTags()).contains("innovative", "reliable", "os", "ai", "gaming");
}
```
Addresses [Enhance Entity Streams with RedisJSON Array commands …
=> Redis JSON ARR* functionality as terminal operations on Entity Streams

redis-om-spring/src/main/java/com/redis/om/spring/RedisJSONKeyValueAdapter.java, redis-om-spring/src/main/java/com/redis/om/spring/RedisModulesConfiguration.java, redis-om-spring/src/main/java/com/redis/om/spring/annotations/Document.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/RedisDocumentRepository.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/support/SimpleRedisDocumentRepository.java, redis-om-spring/src/test/java/com/redis/om/spring/AbstractBaseEnhancedRedisTest.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/DocumentTTLTests.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/TTLTests.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/ExpiringPerson.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/ExpiringPersonDifferentTimeUnit.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/ExpiringPersonDifferentTimeUnitRepository.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/ExpiringPersonRepository.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/ExpiringPersonWithDefault.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/ExpiringPersonWithDefaultRepository.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/RedisHashTTLTests.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/fixtures/ExpiringPerson.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/fixtures/ExpiringPersonDifferentTimeUnit.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/fixtures/ExpiringPersonDifferentTimeUnitRepository.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/fixtures/ExpiringPersonRepository.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/fixtures/ExpiringPersonWithDefault.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/fixtures/ExpiringPersonWithDefaultRepository.java
Provides support for:
* Default TTL for entities using `@Document` just like `@RedisHash` supports https://docs.spring.io/spring-data/redis/docs/current/api/index.html?org/springframework/data/redis/core/TimeToLive.html
* Support for `@TimeToLive` field-level annotation
=> Support @TimeToLive on JSON-mapped objects #66

redis-om-spring/src/main/java/com/redis/om/spring/metamodel/MetamodelGenerator.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/query/Sort.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/ComplexDocumentSearchTest.java, redis-om-spring/src/test/java/com/redis/om/spring/metamodel/MetamodelGeneratorTest.java
In the example below, the `Permit` class has an `Address`, and the address has a `City`. This PR the code generator now generates nested field constants like `Permit$.ADDRESS_CITY`, which corresponds to the search field `address_city` in the schema which in turn corresponds to the (assuming a `Permit p`) to  `p.getAddress().getCity()` code structure.
```
/**
* "FT.SEARCH" "com.redis.om.spring.annotations.document.fixtures.PermitIdx" "house|loft" "SORTBY" "address_city" "DESC"
*/
@Test
void testFullTextSearchWithSortByNestedTextTagFieldDesc() {
String q = "house|loft";
Pageable pageRequest = PageRequest.of(0, 10).withSort(Sort.by(Direction.DESC, Permit$.ADDRESS_CITY));
Page<Permit> result = repository.search(q, pageRequest);
assertThat(result.getTotalPages()).isEqualTo(1); …
```
=> feature: adds convenience generated constants for nested fields in metamodel

redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RediSearchQuery.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RedisEnhancedQuery.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/RedisDocumentWithAliasTest.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/Direccion.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/WithAlias.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/WithAliasRepository.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/RedisHashWithAliasTest.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/fixtures/Direccion.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/fixtures/WithAlias.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/fixtures/WithAliasRepository.java
Scenario: If there is a `@Document` or `@RedisHash` annotated object using aliases for its field, as shown below, the index is build correctly but the queries attempt to use the object field names rather than the aliases.
```
@Document
public class WithAlias {
@Id
private String id;
@NonNull
@TextIndexed(alias = "texto")
private String text;
@NonNull
@TagIndexed(alias = "etiquetas")
private Set<String> tags;
@NonNull
@GeoIndexed(alias = "coordinadas")
private Point location;
@NonNull
@NumericIndexed(alias = "numero")
private Integer number;
@NonNull
@Indexed(alias = "direccion")
private Direccion address;
}
```
Produces:
```
"FT.CREATE" "com.redis.om.spring.annotations.document.fixtures.WithAliasIdx" "ON" "JSON" 
"PREFIX" "1" "com.redis.om.spring.annotations.document.fixtures.WithAlias:" …
```
=> fix: honor indexing annotations 'aliases' when querying (resolves gh-97)

demos/roms-documents/pom.xml, demos/roms-hashes/pom.xml, demos/roms-permits/pom.xml
Enable releases and draft releases by skipping the demo project which should not be released
=> build: skip demo project during deploys (maven.deploy.skip in POM)

demos/roms-documents/pom.xml, demos/roms-hashes/pom.xml, demos/roms-permits/pom.xml, redis-om-spring/pom.xml, redis-om-spring/src/main/java/com/redis/om/spring/metamodel/MetamodelField.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/ReturnFieldsSearchStreamImpl.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/SearchStream.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/SearchStreamImpl.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/WrapperSearchStream.java, redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamsAggregationsTest.java
Implements `min` and `max` methods for `SearchStream` using aggregations:
```java
// The wrong way... pulling everything and using Java
Optional<Game> minPriceGame1 = entityStream //
.of(Company.class) //
.min((g1, g2) -> g1.getPrice().compareTo(g2.getPrice()));
// The long way... using aggregations streams
List<Pair<String, Double>> minAggregation = entityStream.of(Game.class) //
.load(Game$._KEY) //
.sorted(Game$.PRICE.asc())
.limit(1) //
.toList(String.class, Double.class);
Pair<String,Double> expected = minAggregation.get(0);
// The short way...
Optional<Game> minPriceGame2 = entityStream.of(Game.class).min(Game$.PRICE);
```
=> shortcut aggregations for Streams min/max

redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RediSearchQuery.java, redis-om-spring/src/test/java/com/redis/om/spring/RedisJSONKeyValueAdapterTest.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/BasicRedisDocumentMappingTest.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/Company.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/CompanyMeta.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/CompanyRepository.java
Enables repository queries like:
```java
List<Company> findByMetaList_stringValue(String value);
List<Company> findByMetaList_numberValue(Integer value);
List<Company> findByMetaList_tagValues(Set<String> tags);
```
Given an entity with an Set/List like:
```java
@Document
public class Company {
@Indexed
private Set<CompanyMeta> metaList;
}
@Data
public class CompanyMeta {
@Indexed
@NonNull
private String stringValue;
@Indexed
@NonNull
private Integer numberValue;
@Indexed
@NonNull
private Set<String> tagValues;
}
```
=> feature: enable repository queries on nested Set/List entity members

redis-om-spring/src/main/java/com/redis/om/spring/repository/support/SimpleRedisDocumentRepository.java
Remove cast to a String as the ID can be other types other than a String.
NonStandardDocumentSearchTest should cover this case
relates to https://github.com/redis/redis-om-spring/issues/172
=> Remove cast to a String as the ID can be other types other than a String

redis-om-spring/src/main/java/com/redis/om/spring/RedisJSONKeyValueAdapter.java, redis-om-spring/src/main/java/com/redis/om/spring/RedisModulesConfiguration.java, redis-om-spring/src/main/java/com/redis/om/spring/RedisOMSpringProperties.java, redis-om-spring/src/test/java/com/redis/om/spring/AbstractBaseDocumentTest.java, redis-om-spring/src/test/java/com/redis/om/spring/repository/SimpleDocument.java, redis-om-spring/src/test/java/com/redis/om/spring/repository/SimpleDocumentRepository.java, redis-om-spring/src/test/java/com/redis/om/spring/repository/SimpleDocumentTest.java, redis-om-spring/src/test/resources/application.yaml
I've recognized that only the first 10 elements are returned when querying all elements from a repository. This was also reported in [this StackOverflow thread](https://stackoverflow.com/questions/72948903/returning-only-the-first-10-record-redis-om).
This PR attempts to fix this behaviour by providing a configuration option for this value. The default value is 10 to prevent a breaking change. Users may set it to `Integer.MAX_VALUE` to retrieve all elements from a repository.
=> feature: add a configuration parameter to specify the default query limit

redis-om-spring/src/main/java/com/redis/om/spring/RedisModulesConfiguration.java
The `RedisModulesConfiguration` class implements the `CachingConfigurer` interface, but neither overrides nor uses a method from it. However, the implementation of the interface in a configuration class registeres a bean that may clash with an other caching configuration in an application. This PR therefore simply removes the interface declaration.
=> Remove CachingConfigurer interface in `RedisModulesConfiguration`

redis-om-spring/src/main/java/com/redis/om/spring/search/stream/SearchStreamImpl.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/Doc.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/DocRepository.java, redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamsIssuesTest.java
Fixes issue with dependency on the order of `.filter(freeText)` method in EntityStream searches - see gh-176
CC @rjdkolb
=> fix: resolve .filter(freetext) order independent (resolves gh-176)

demos/roms-documents/pom.xml, redis-om-spring/src/main/java/com/redis/om/spring/DistanceMetric.java, redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java, redis-om-spring/src/main/java/com/redis/om/spring/VectorType.java, redis-om-spring/src/main/java/com/redis/om/spring/annotations/Indexed.java, redis-om-spring/src/main/java/com/redis/om/spring/annotations/SchemaFieldType.java, redis-om-spring/src/main/java/com/redis/om/spring/annotations/VectorIndexed.java, redis-om-spring/src/main/java/com/redis/om/spring/metamodel/MetamodelField.java, redis-om-spring/src/main/java/com/redis/om/spring/metamodel/MetamodelGenerator.java, redis-om-spring/src/main/java/com/redis/om/spring/metamodel/indexed/VectorField.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/ReturnFieldsSearchStreamImpl.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/SearchStreamImpl.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/predicates/vector/KNNPredicate.java, redis-om-spring/src/test/java/com/redis/om/spring/AbstractBaseOMTest.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/DocRepositoriesAutoDiscoveryTest.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/RedisHashVSSIndexCreationTest.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/RedisHashVSSTest.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/fixtures/HashWithByteArrayFlatVector.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/fixtures/HashWithByteArrayFlatVectorRepository.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/fixtures/HashWithByteArrayHNSWVector.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/fixtures/HashWithByteArrayHNSWVectorRepository.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/fixtures/HashWithVectors.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/fixtures/HashWithVectorsRepository.java, redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamTest.java, redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamsHashVSSTests.java
I'm putting together the API for VSS as part of Redis OM Spring EntityStreams API, I'm working on an example-driven basis, starting with the demo 
at https://github.com/RedisAI/Java-VSS-demo which uses Jedis 4.x, current example I'm trying to reproduce it using Hashes:
Creates an index with 2 fields, the vector `"my_vector"` and a numeric `"number"`:
```java
public void create_hnsw_index (UnifiedJedis redis_conn, String vector_field_name, int number_of_vectors, int vector_dimensions, String distance_metric, int m, int ef) {
Map<String, Object> attr = new HashMap<>();
attr.put("TYPE", "FLOAT32");
attr.put("DIM", vector_dimensions);
attr.put("DISTANCE_METRIC", distance_metric);
attr.put("INITIAL_CAP", number_of_vectors);
attr.put("M", m);
attr.put("EF_CONSTRUCTION", ef);
Schema schema = new …
```
=> Vector Similarity Search

redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RediSearchQuery.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RedisEnhancedQuery.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/RepositoryIssuesTest.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/User2.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/User2Repository.java
Handles param substitution in queries when params share a prefix using a regex to replace rather than just a simple string matching.
For example ` @Query("(@name:{$name}) (@address:{$address}) (@addressComplement:{$addressComp})")`
Replacing with `String.replace` the value `$address` would also partially replace `$addressComp`, instead use `String.replaceAll(regex, val)`
=> fix: handles parameters that share a prefix in queries (resolves gh-187)

redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java, redis-om-spring/src/main/java/com/redis/om/spring/RedisModulesConfiguration.java, redis-om-spring/src/main/java/com/redis/om/spring/autocomplete/AutoCompleteAspect.java, redis-om-spring/src/main/java/com/redis/om/spring/bloom/BloomAspect.java, redis-om-spring/src/main/java/com/redis/om/spring/convert/MappingRedisOMConverter.java, redis-om-spring/src/main/java/com/redis/om/spring/metamodel/MetamodelGenerator.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RediSearchQuery.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RedisEnhancedQuery.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/query/autocomplete/AutoCompleteQueryExecutor.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/query/bloom/BloomQueryExecutor.java, redis-om-spring/src/main/java/com/redis/om/spring/util/ObjectUtils.java, redis-om-spring/src/test/java/com/redis/om/spring/metamodel/MetamodelGeneratorTest.java, redis-om-spring/src/test/java/com/redis/om/spring/repository/AbstractDocument.java, redis-om-spring/src/test/java/com/redis/om/spring/repository/InheritingDocument.java, redis-om-spring/src/test/java/com/redis/om/spring/repository/InheritingDocumentRepository.java, redis-om-spring/src/test/java/com/redis/om/spring/repository/InheritingDocumentTest.java, redis-om-spring/src/test/java/com/redis/om/spring/util/ObjectUtilsTest.java
As described in #203, currently only fields in the `@Document` annotated class can have `@Id` or `@Indexed` annotations and annotations on fields from superclasses are not processed.
This PR attempts to resolve this issue. Therefore all fields are retrieved through the class hierarchy up to the `Object` class. To properly retrieve `private` fields, the JDK's reflection method `getFields()` can't be used. For now, recursion is used to traverse the class hierarchy and all `private` fields are retrieved via `getDeclaredFields()`.
=> Support annotations on private fields of superclasses of documents

redis-om-spring/src/main/java/com/redis/om/spring/RedisModulesConfiguration.java
Backport for #181
The `RedisModulesConfiguration` class implements the `CachingConfigurer` interface, but neither overrides nor uses a method from it. However, the implementation of the interface in a configuration class registeres a bean that may clash with an other caching configuration in an application. This PR therefore simply removes the interface declaration.
=> Remove `CachingConfigurerSupport` superclass in `RedisModulesConfiguration`

README.md, redis-om-spring/src/main/java/com/redis/om/spring/RedisJSONKeyValueAdapter.java
To lookup an entity class in the (Spring Data Redis) KeyspaceConfiguration, the class object to lookup has to be loaded with the System Class Loader, but then the same class object cannot be used when finding the getter to reflectively invoke the assigned TTL getter method on a given entity. This PR separates the lookup from the reflection parts of this procedure.
=> Issue 236 - Fixes "Fail setting TTL from property during save operation"

demos/roms-vss/src/main/resources/application.properties, pom.xml, redis-om-spring/pom.xml, redis-om-spring/src/main/java/com/redis/om/spring/RedisModulesConfiguration.java, redis-om-spring/src/main/java/com/redis/om/spring/vectorize/DefaultFeatureExtractor.java, redis-om-spring/src/main/java/com/redis/om/spring/vectorize/FeatureExtractor.java
I want to make injectable FeatureExtractor because I don't need DJL. So everyone now can implement FeatureExtractor or use the provided DefaultFeatureExtractor.
Also removed `@Component` to avoid auto discovery (the bean is declared in configuration).
=> Make FeatureExtractor injectable

redis-om-spring/pom.xml, redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java, redis-om-spring/src/main/java/com/redis/om/spring/RedisModulesConfiguration.java, redis-om-spring/src/main/java/com/redis/om/spring/metamodel/MetamodelGenerator.java, redis-om-spring/src/main/java/com/redis/om/spring/metamodel/MetamodelUtils.java, redis-om-spring/src/main/java/com/redis/om/spring/ops/RedisModulesOperations.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/RedisDocumentRepository.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/RedisEnhancedRepository.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/support/SimpleRedisDocumentRepository.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/support/SimpleRedisEnhancedRepository.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/EntityStreamImpl.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/ExampleToNodeConverter.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/FluentQueryByExample.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/ReturnFieldsSearchStreamImpl.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/SearchStream.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/SearchStreamImpl.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/WrapperSearchStream.java, redis-om-spring/src/main/java/com/redis/om/spring/util/ObjectUtils.java, redis-om-spring/src/main/java/com/redis/om/spring/util/SearchResultRawResponseToObjectConverter.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/RedisDocumentQueryByExampleTest.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/Doc3.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/Doc3Repository.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/RedisHashQueryByExampleTest.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/fixtures/MyHashRepository.java, redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamDocsTest.java, redis-om-spring/src/test/java/com/redis/om/spring/util/ObjectUtilsTest.java, redis-om-spring/src/test/java/com/redis/om/spring/util/SearchResultRawResponseToObjectConverterTest.java
See https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#query-by-example
=> Feature: Implements Query By Example (QBE)

redis-om-spring/src/main/java/com/redis/om/spring/annotations/Indexed.java, redis-om-spring/src/main/java/com/redis/om/spring/metamodel/MetamodelGenerator.java
Fixed a stack overflow issue during compilation.
Now the depth of creating a metamodel for a field of the same class will be equal to 1, if necessary, it can be increased by the “depth” parameter in the “Indexed” annotation.
I've also removed some code duplication and moved some class creation out of the method logic for easier readability.
ps. I think that for the project it is worth using some kind of single check style.
=> #293 fixed infinite nested loop during metamodel creation

.github/workflows/spellcheck.yml
Hello
As the maintainer of the [spellcheck GitHub action](https://github.com/marketplace/actions/github-spellcheck-action) I am _sunsetting_ version 0.23.0 as by the proposed [sunset policy](https://github.com/rojopolis/spellcheck-github-actions/wiki#sunset-policy)
I just updated the action to version 0.35.0, so this PR offers an update to the latest version.
Let me know if you have any issues with the proposed PR and I will do my best to accommodate.
I can recommend [Dependabot](https://github.com/dependabot) for keeping your GitHub actions up to date, alternatively there are [Renovate](https://github.com/marketplace/renovate), if you want a PR proposing a basic configuration for Dependabot, please let me know.
jonasbn
=> build: Bumped spellcheck action to latest version, since 0.23.0 is EOL

README.md, demos/roms-documents/pom.xml, demos/roms-hashes/pom.xml, demos/roms-permits/pom.xml, demos/roms-vss/pom.xml, pom.xml, redis-om-spring/pom.xml
Spring Boot 3.2 release:
- feature: Add support for UUIDs and ULIDs as TAG indexable field (resolves gh-364) 
- feature: adds Redis sentinel support (resolves gh-227)
- refactor: removed commented out code 
- refactor: Use FTCreateParams for ftCreate method, update Jedis constants for VSS 
- refactor: clean up, warnings, deprecations
- refactor: upgrade all Jedis calls to RedisJsonV2Commands
- refactor: removed unused class EnhancedRedisQueryEngine
- release: 0.8.8-SNAPSHOT - Spring Boot 3.2
- dependencies: update spring/sdr to 3.1.7 and all sub-deps
- Bumped spellcheck action to latest version, since 0.23.0 is EOL
- fixed infinite nested loop during metamodel creation
- Minor tweaks to README 
- refactor: clean up VSS demo
- fix: prevent index out of bounds on nocontent empty query …
=> release: version 0.8.8

redis-om-spring/pom.xml, redis-om-spring/src/main/java/com/redis/om/spring/RedisModulesConfiguration.java, redis-om-spring/src/main/java/com/redis/om/spring/RedisOMProperties.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/support/SimpleRedisDocumentRepository.java, redis-om-spring/src/main/java/com/redis/om/spring/serialization/gson/GsonReferenceSerializerRegistrar.java, redis-om-spring/src/main/java/com/redis/om/spring/serialization/gson/ReferenceDeserializer.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/ReferenceTest.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/Ref.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/RefRepository.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/TooManyReferences.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/TooManyReferencesRepository.java, redis-om-spring/src/test/resources/application.yaml
@Reference fields can causes bursts of JSON.GET commands (N+1 type of problem) - this enables in-memory caching of the resolves references using Spring Caching mechanism.
=> feature: enhanced reference deserializer and on-demand reference cache

demos/roms-documents/pom.xml, demos/roms-hashes/pom.xml, demos/roms-permits/pom.xml, demos/roms-vss/pom.xml, pom.xml, redis-om-spring/pom.xml, redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RediSearchQuery.java
This is a naive fix for #483 .
It is supposed to treat document results that just-expired as inexistent.
=> fix: treat just-expired document as inexistent

README.md
The README indicates that a new repository is required due to the new spring-ai dependency, but it says greater than 0.9.2 when it should be starting at 0.9.2 or greater than 0.9.1.
=> docs: fix version requiring spring-milestones in Maven snippets in README

redis-om-spring/src/main/java/com/redis/om/spring/RedisEnhancedKeyValueAdapter.java
KeyValueAdapter for HASHES issues two commands on it `put` method, a `DEL` and `HMSET`.  This PR wraps them both in pipeline call.
=> fix: RedisEnchanceKeyValueAdapter#put make DEL/HMSET combo in a pipeline

.github/workflows/codeql-analysis.yml, .github/workflows/integration.yml, .github/workflows/snapshot.yml, .github/workflows/version-and-release.yml, README.md, demos/roms-documents/pom.xml, demos/roms-hashes/pom.xml, demos/roms-permits/pom.xml, demos/roms-vss/pom.xml, pom.xml, redis-om-spring/pom.xml, redis-om-spring/src/main/java/com/redis/om/spring/RedisOMProperties.java, redis-om-spring/src/main/java/com/redis/om/spring/metamodel/MetamodelGenerator.java
This PR modifies the metamodel generator to handle the latest JVM version and set the current compilation/distribution to use Java 21
=> Java 21 support

redis-om-spring/pom.xml
I ran another test: 
1. Remove Spring AI BOM folder from .m2:
`rm -rf ~/.m2/repository/org/springframework/ai/spring-ai-bom`
2. Reload Maven project:
2.1. with Redis OM Spring v0.9.8:
Directory and contents are recreated
2.2. with a new snapshot of Redis OM Spring without Spring AI BOM:
Directory and contents are not recreated. 
Turns out that even though Maven won't download the actual dependencies (and that's why nothing shows in the dependency tree), it will still import the POM file of the BOM. To avoid this from happening, I simply removed the BOM and managed the versions of Spring AI optional dependencies manually.
=> Removing Spring AI BOM

redis-om-spring/src/main/java/com/redis/om/spring/RedisOMAiProperties.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/support/SimpleRedisDocumentRepository.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/support/SimpleRedisEnhancedRepository.java, redis-om-spring/src/main/java/com/redis/om/spring/vectorize/DefaultEmbedder.java, redis-om-spring/src/main/java/com/redis/om/spring/vectorize/Embedder.java, redis-om-spring/src/main/java/com/redis/om/spring/vectorize/NoopEmbedder.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/vectorize/VectorizeDocumentTest.java, redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/vectorize/VectorizeHashTest.java
Work In Progress
Within saveAll methods (SimpleRedisEnhancedRepository & SimpleRedisDocumentRepository): 
- Calling new processEntities() before iterating through all entities. 
processEntities():
- Based on processEntity()
- Uses embedding functions to create embeddings in bulks 
- Remap created embeddings into the original entity list (destination field)
Methods for creating bulk embeddings already existed for sentence embeddings, but had to be created for image and face embeddings. 
DefaultEmbedder: 
- Cleaned up
Tests: 
- To test embeddings are created and mapped correctly, I use the existing Vectorize Test classes and compare the embeddings of the saveAll method with the embeddings of the save method. 
Will create benchmarks to compare bulk embedding with original implementation.
=> Using bulk APIs/calls on entities during saveAll

tests/src/test/java/com/redis/om/spring/annotations/document/RepositoryIssuesTest.java, tests/src/test/java/com/redis/om/spring/fixtures/document/model/Doc5.java, tests/src/test/java/com/redis/om/spring/fixtures/document/repository/Doc5Repository.java
Add test cases to verify that findByIsActive and findByRegistrationDateBetween query methods work correctly with indexed Boolean and LocalDateTime fields.
- Add Doc5 model with indexed Boolean and LocalDateTime fields
- Add Doc5Repository with query methods
- Add test methods to RepositoryIssuesTest for these query types
=> test: add test cases for boolean and datetime query methods

redis-om-spring/src/main/java/com/redis/om/spring/RedisAiConfiguration.java, redis-om-spring/src/main/java/com/redis/om/spring/RedisOMAiProperties.java, redis-om-spring/src/main/java/com/redis/om/spring/annotations/Vectorize.java, redis-om-spring/src/main/java/com/redis/om/spring/vectorize/DefaultEmbedder.java, redis-om-spring/src/main/java/com/redis/om/spring/vectorize/EmbeddingModelFactory.java, redis-om-spring/src/main/java/com/redis/om/spring/vectorize/SpringAiProperties.java, redis-om-spring/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- I've been playing with embedding in bulk and constantly facing read timeouts. 
- Default read timeout configured for OpenAI Embedding Model is 10 seconds
- I tried to overwrite the OpenAiEmbeddingModel bean, but find out that it only matters if we're using the default Embedding Model. 
- If using a different embedding model, the DefaultEmbedder bean will create a new OpenAiEmbeddingModel that cannot be overwritten. 
Therefore I suggest: 
- We get rid of the default embedding model beans and replace them with:
- We create an EmbeddingModelFactory where we have the blueprint of what the embedding models should look like. The creation methods receive the model which the created EmbeddingModel will serve. 
- We support specifying the embedding model only through the Vectorize annotation …
=> Ability to set read timeout for OpenAI Embedding Model Rest Client + design proposal

.gitignore, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/ReturnFieldsSearchStreamImpl.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/SearchStream.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/SearchStreamImpl.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/WrapperSearchStream.java, tests/src/test/java/com/redis/om/spring/search/stream/EntityStreamConditionalFiltersDocumentTest.java, tests/src/test/java/com/redis/om/spring/search/stream/EntityStreamConditionalFiltersHashTest.java
feat: add conditional filtering methods to SearchStream
- Add filterIfNotNull to apply filters only when values are not null
- Add filterIfNotBlank to apply filters only when strings are not null or blank
- Add filterIfPresent to apply filters only when Optional values are present
- Use Supplier interface to lazily create predicates only when needed
- Add comprehensive test coverage for Document and Hash entities
- Improve customer query use case with more readable filtering syntax
=> EntityStreams conditional filters

tests/README.md, tests/pom.xml, tests/src/test/java/com/redis/om/spring/AbstractBaseDocumentSentinelTest.java, tests/src/test/java/com/redis/om/spring/annotations/document/sentinel/AdvancedSentinelTest.java, tests/src/test/java/com/redis/om/spring/annotations/document/sentinel/BasicSentinelTest.java, tests/src/test/java/com/redis/om/spring/annotations/document/sentinel/SentinelConfigTest.java, tests/src/test/java/com/redis/om/spring/fixtures/document/repository/CompanyRepository.java, tests/src/test/resources/sentinel/docker/docker-compose.yml, tests/src/test/resources/sentinel/docker/sentinel.conf
- Add AbstractBaseDocumentSentinelTest using TestContainers
- Create BasicSentinelTest for CRUD operations via Sentinel
- Implement AdvancedSentinelTest for complex queries via Sentinel
- Add SentinelConfigTest with unit tests for configuration class
- Improve sentinel docker-compose configuration
- Add tests README.md with Sentinel setup documentation
- Upgrade TestContainers Redis version to 2.2.4
=> feat: implement Redis Sentinel support with comprehensive test suite

redis-om-spring/src/main/java/com/redis/om/spring/RedisModulesConfiguration.java, redis-om-spring/src/main/java/com/redis/om/spring/annotations/CountMin.java, redis-om-spring/src/main/java/com/redis/om/spring/countmin/CountMinAspect.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RediSearchQuery.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RedisEnhancedQuery.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/query/countmin/CountMinQueryExecutor.java, tests/src/test/java/com/redis/om/spring/annotations/countmin/CountMinTest.java, tests/src/test/java/com/redis/om/spring/fixtures/hash/model/SearchEvent.java, tests/src/test/java/com/redis/om/spring/fixtures/hash/repository/SearchEventRepository.java, tests/src/test/java/com/redis/om/spring/fixtures/hash/repository/UserIdCount.java, tests/src/test/java/com/redis/om/spring/fixtures/hash/repository/UserIdCountImpl.java
This PR adds support for the Count-min Sketch probabilistic data structure to Redis OM Spring as an annotation, complementing the existing Bloom and Cuckoo filter annotation implementations.
- New @CountMin annotation for entity fields
- Support for two initialization modes:
- By dimensions (width and depth)
- By probability (error rate and probability)
- Automatic sketch creation and deletion (when deleteAll is invoked)
- Support for counting single values and collections
- Dynamic repository methods for count queries
- Custom repository implementations for advanced use cases
=> feat: annotation for count min sketch

redis-om-spring/src/main/java/com/redis/om/spring/search/stream/SearchStreamImpl.java, tests/src/test/java/com/redis/om/spring/search/stream/DialectSpaceFilterTest.java
- Fixes issue #579 where spaces at the beginning of query strings caused syntax errors
- The fix trims leading/trailing spaces from query strings before adding the DIALECT parameter
- Uses configured dialect value instead of hardcoded value
- Added test cases to verify proper handling of spaces in filter queries
=> fix: Trim query string to handle spaces with DIALECT parameter (#579)

redis-om-spring/src/main/java/com/redis/om/spring/search/stream/SearchStreamImpl.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/predicates/fulltext/LikePredicate.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/predicates/fulltext/NotLikePredicate.java, tests/src/test/java/com/redis/om/spring/fixtures/document/model/TextContent.java, tests/src/test/java/com/redis/om/spring/fixtures/document/repository/TextContentRepository.java, tests/src/test/java/com/redis/om/spring/search/stream/WildcardSearchTest.java
Implements wildcard support for the like() and notLike() operators:
- Modified LikePredicate and NotLikePredicate to support SQL wildcards (%)
- Implemented conversion of SQL-like wildcards (%) to Redis wildcards (*)
- Added special case handling for different wildcard positions (prefix, suffix, infix)
=> feat: Add wildcard support for like/notLike operators (#532)

.github/workflows/docs.yml, .gitignore, build.gradle, docs/Makefile, docs/README.md, docs/antora-playbook.yml, docs/build.gradle, docs/content/modules/ROOT/nav.adoc, docs/content/modules/ROOT/pages/api-reference.adoc, docs/docker-compose.yml, docs/nginx.conf, docs/scripts/clean-generated-javadoc.sh, docs/scripts/rebuild-with-javadoc.sh, docs/scripts/test-local-docs.sh, docs/scripts/validate-javadoc.sh, docs/supplemental-ui/css/redis-brand.css
- Add aggregated Javadoc generation tasks for redis-om-spring and redis-om-spring-ai modules
- Create API reference page with navigation links to module documentation
- Configure Antora attachments integration for Javadoc HTML files
- Update GitHub Actions workflow to generate and deploy Javadoc automatically
- Add build scripts for local Javadoc generation and validation
- Exclude generated Javadoc files from version control via .gitignore
- Implement cleanup mechanisms for proper build artifact management
=> feat(docs): integrate Javadoc into Antora documentation site

docs/content/modules/ROOT/pages/entity-streams.adoc, docs/content/modules/ROOT/pages/index-annotations.adoc, docs/content/modules/ROOT/pages/metamodel.adoc
Added comprehensive documentation for the new NumericField array search capabilities:
1. **entity-streams.adoc**: Added "Numeric Array Queries" section with examples of containsDouble(), containsLong(), and containsInt() methods for EntityStream filtering
2. **metamodel.adoc**: Added "Numeric Array Field Methods" section explaining the generated metamodel methods for type-safe numeric array containment searches
3. **index-annotations.adoc**: Added examples of indexing numeric arrays/collections and cross-referenced to the numeric array query documentation
These methods provide functionality similar to TagField.in() but specifically designed for numeric arrays, addressing GitHub issue #400.
=> docs: add documentation for numeric array containment search methods

redis-om-spring/src/main/java/com/redis/om/spring/search/stream/predicates/tag/EqualPredicate.java, tests/src/test/java/com/redis/om/spring/search/stream/predicates/tag/TagEqualPredicateRegressionTest.java
Fix regression introduced in v0.9.10 where tag field equality predicates incorrectly escape quotes, causing Redis syntax errors.
=> fix: EqualPredicate changes in 0.9.10 breaking search syntax (#609)

redis-om-spring/src/main/java/com/redis/om/spring/ops/json/JSONOperationsImpl.java, redis-om-spring/src/main/java/com/redis/om/spring/serialization/gson/ReferenceDeserializer.java, tests/src/test/java/com/redis/om/spring/annotations/document/ReferenceTest.java
- Add null checks in ReferenceDeserializer to prevent NPE when referenced entities are missing
- Add null check in JSONOperationsImpl.get() to handle null results from Redis
- Log warnings when referenced entities cannot be found
- Filter out missing references from collections instead of throwing NPE
- Add tests to verify proper handling of missing single and collection references
=> fix: handle missing @Reference entities gracefully (#607)

redis-om-spring/src/main/java/com/redis/om/spring/RedisEnhancedKeyValueAdapter.java, redis-om-spring/src/main/java/com/redis/om/spring/RedisJSONKeyValueAdapter.java, redis-om-spring/src/main/java/com/redis/om/spring/annotations/RedisKey.java, redis-om-spring/src/main/java/com/redis/om/spring/mapping/RedisEnhancedPersistentEntity.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RediSearchQuery.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RedisEnhancedQuery.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/support/SimpleRedisDocumentRepository.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/support/SimpleRedisEnhancedRepository.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/SearchStreamImpl.java, redis-om-spring/src/main/java/com/redis/om/spring/util/ObjectUtils.java, tests/src/test/java/com/redis/om/spring/annotations/document/RedisKeyCustomPrefixTest.java, tests/src/test/java/com/redis/om/spring/annotations/document/RedisKeyTest.java, tests/src/test/java/com/redis/om/spring/annotations/hash/RedisKeyCustomPrefixHashTest.java, tests/src/test/java/com/redis/om/spring/annotations/hash/RedisKeyHashTest.java, tests/src/test/java/com/redis/om/spring/fixtures/document/model/DocWithCustomPrefixAndRedisKey.java, tests/src/test/java/com/redis/om/spring/fixtures/document/model/DocWithRedisKey.java, tests/src/test/java/com/redis/om/spring/fixtures/document/repository/DocWithCustomPrefixAndRedisKeyRepository.java, tests/src/test/java/com/redis/om/spring/fixtures/document/repository/DocWithRedisKeyRepository.java, tests/src/test/java/com/redis/om/spring/fixtures/hash/model/HashWithCustomPrefixAndRedisKey.java, tests/src/test/java/com/redis/om/spring/fixtures/hash/model/HashWithRedisKey.java, tests/src/test/java/com/redis/om/spring/fixtures/hash/repository/HashWithCustomPrefixAndRedisKeyRepository.java, tests/src/test/java/com/redis/om/spring/fixtures/hash/repository/HashWithRedisKeyRepository.java
Add a new @RedisKey annotation that allows entities to capture their Redis key during retrieval operations. This feature enables entities to know their full Redis key, which is useful for operations that need the complete key, including custom prefixes.
- Add @RedisKey field annotation for marking fields to receive Redis keys
- Implement populateRedisKey utility method with class-level caching for performance
- Integrate key population into all entity retrieval paths (adapters, repositories, queries)
- Add optimized metadata caching in RedisEnhancedPersistentEntity with lazy initialization
- Support both Document and Hash entities with default and custom key prefixes
- Add comprehensive test coverage for all entity types and key prefix scenarios
=> feat: add @RedisKey annotation to populate entity fields with Redis  keys during search operations (#538)

docs/content/modules/ROOT/pages/entity-streams-aggregations.adoc, docs/content/modules/ROOT/pages/entity-streams.adoc, docs/content/modules/ROOT/pages/overview.adoc, docs/content/modules/ROOT/pages/query-annotation.adoc, docs/content/modules/ROOT/pages/repository-queries.adoc, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/AggregationStream.java, redis-om-spring/src/main/java/com/redis/om/spring/search/stream/AggregationStreamImpl.java, tests/src/test/java/com/redis/om/spring/search/stream/AggregationHashProjectionTest.java, tests/src/test/java/com/redis/om/spring/search/stream/AggregationProjectionTest.java
Implements Spring Data-style projections and map-based results for aggregations, providing flexible alternatives to tuple-based results. Follows Spring Data conventions where IDs are not automatically included in projections.
- Add toProjection(Class<P>) method for interface-based projections
- Add toMaps() and toMaps(boolean includeId) for map-based results
- Projections follow Spring Data JPA pattern (IDs not auto-included)
- Maps include IDs by default with option to exclude
- Dynamic proxy implementation for projection interfaces
- Type conversion support for common types
- Comprehensive tests for both document and hash entities
- Documentation with examples and comparison of approaches
=> feat: add projection and map support for aggregations (#539)

redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RediSearchQuery.java, tests/src/test/java/com/redis/om/spring/fixtures/document/repository/CompanyRepository.java, tests/src/test/java/com/redis/om/spring/fixtures/document/repository/CompanyRepositoryWithLimiting.java, tests/src/test/java/com/redis/om/spring/repository/query/FindTopLimitingTest.java
- Add PartTree limit checking in RediSearchQuery.processPartTree()
- Methods like findTop2ByOrderByNameAsc now correctly pass limit to Redis
- Fixes issue where all methods returned default 10000 results
- Add comprehensive tests for various limiting scenarios
Fixes #630
=> fix: add limit support for findTop/findFirst repository methods

README.md, docs/content/modules/ROOT/nav.adoc, docs/content/modules/ROOT/pages/quickstart.adoc, docs/content/modules/ROOT/pages/version-requirements.adoc
- Document N-2 version support policy in README
- Create dedicated version-requirements.adoc page in docs
- Add comprehensive version compatibility matrix
- Include upgrade guidance and dependency alignment examples
- Update quickstart prerequisites with version info
Fixes #520
=> docs: add Spring Boot version requirements and compatibility policy

.gitignore, docs/content/modules/ROOT/pages/json-map-fields.adoc, docs/content/modules/ROOT/pages/json_mappings.adoc, redis-om-spring/src/main/java/com/redis/om/spring/indexing/RediSearchIndexer.java, redis-om-spring/src/main/java/com/redis/om/spring/metamodel/MetamodelGenerator.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RediSearchQuery.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/query/clause/QueryClause.java, tests/src/test/java/com/redis/om/spring/annotations/document/MapComplexObjectIndexingTest.java, tests/src/test/java/com/redis/om/spring/annotations/document/MapComplexObjectTest.java, tests/src/test/java/com/redis/om/spring/fixtures/document/model/AccountWithPositions.java, tests/src/test/java/com/redis/om/spring/fixtures/document/model/Position.java, tests/src/test/java/com/redis/om/spring/fixtures/document/repository/AccountWithPositionsRepository.java
Extends Redis OM Spring to support repository method patterns like
findByPositionsMapContainsCusip for querying nested fields within
Map values containing complex objects. This enables RDI-compatible
queries such as @positions_cusip:{AAPL} without requiring @Query
annotations.
- Add MapContains pattern detection in QueryClause for nested fields
- Extend MetamodelGenerator to create metamodel fields for Map nested properties
- Implement special query processing in RediSearchQuery for MapContains patterns
- Support both simple Map value queries and complex nested field queries
- Enable numeric comparisons on nested fields (GreaterThan, Between, etc.)
This allows Spring Data repository methods to naturally express queries
on nested fields within Map values, matching the RDI index structure …
=> feat: add native repository method support for querying nested fields in Map<String, ComplexObject>

redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RediSearchQuery.java, tests/src/test/java/com/redis/om/spring/annotations/document/MapComplexObjectUpperCaseTest.java, tests/src/test/java/com/redis/om/spring/fixtures/document/model/AccountUC.java
Modified processMapContainsQuery to support Map fields with uppercase/non-standard casing (e.g., 'Positions' instead of 'positions'). The method now tries both the standard lowercase naming convention and the original field name when resolving Map fields.
This fixes repository methods like findByPositionsMapContainsCusip when the Java field uses non-standard casing to match JSON data from external sources like RIOT exports.
=> fix: handle non-standard field casing in MapContains queries

docs/content/modules/ROOT/pages/hash-mappings.adoc, redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RediSearchQuery.java, redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RedisEnhancedQuery.java, tests/src/test/java/com/redis/om/spring/fixtures/hash/model/HashWithSearchStream.java, tests/src/test/java/com/redis/om/spring/fixtures/hash/repository/HashWithSearchStreamRepository.java, tests/src/test/java/com/redis/om/spring/repository/SearchStreamHashRepositoryTest.java, tests/src/test/java/com/redis/om/spring/repository/SearchStreamRepositoryTest.java
Add support for repositories to return SearchStream for fluent query operations. This enables combining Spring Data repository methods with Entity Stream capabilities for both JSON documents and Redis Hashes.
Changes:
- Implement SearchStream detection and handling in RediSearchQuery for JSON documents
- Implement SearchStream detection and handling in RedisEnhancedQuery for Redis Hashes
- Create EntityStream instances that are configured with query filters
- Support lazy execution when terminal operations are called
Documentation:
- Add Entity Streams Integration section to hash-mappings.adoc
- Update comparison table to mention SearchStream return capability
This feature allows repository methods to return SearchStream<T> enabling:
- Fluent filtering with field predicates
- Mapping and …
=> feat: add SearchStream return type support for repository methods

README.md
Updated README to reflect that Redis OM Spring is now production-ready at version 1.0.4, removing the "preview release" terminology that was no longer accurate.
=> docs: remove outdated preview release language from README
