.circleci.settings.xml
.circleci/config.yml
.github/release-drafter-config.yml
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/release-drafter.yml
.github/workflows/version-and-release.yml
demos/roms-documents/pom.xml
demos/roms-hashes/pom.xml
redis-om-spring/pom.xml

Changes to build based on https://central.sonatype.org/publish/publish-maven/

OSSRH Maven Changes

---

README.md

- Adds badges 
- Clean formatting

docs: README cleanup

---

.gitignore
redis-om-spring/src/main/java/com/redis/om/spring/repository/support/RedisDocumentRepositoryFactoryBean.java

fix: change autowiring of RedisModulesOperations in RedisDocumentRepositoryFactoryBean to annotation

---

demos/roms-permits/src/main/java/com/redis/om/permits/PermitsApplication.java
demos/roms-permits/src/main/java/com/redis/om/permits/models/Attribute.java
demos/roms-permits/src/main/java/com/redis/om/permits/models/Order.java
demos/roms-permits/src/main/java/com/redis/om/permits/models/Permit.java
demos/roms-permits/src/main/java/com/redis/om/permits/repositories/PermitRepository.java
redis-om-spring/src/main/java/com/redis/om/spring/RedisModulesConfiguration.java
redis-om-spring/src/main/java/com/redis/om/spring/annotations/Indexed.java
redis-om-spring/src/main/java/com/redis/om/spring/annotations/Nested.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RediSearchQuery.java
redis-om-spring/src/main/java/com/redis/om/spring/util/ObjectUtils.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/BasicRedisDocumentMappingTest.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/Company.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/CompanyRepository.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/Employee.java

Add @Nested annotation to support indexing multi-level nested object arrays.

Support indexing multi-level nested object arrays.

---

redis-om-spring/src/test/java/com/redis/om/spring/AbstractBaseDocumentTest.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/RedisDocumentSearchTest.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/MyDocRepository.java

Adds a test to back the answer to https://github.com/redis/redis-om-spring/issues/49

test: add test for @Query annotation with Pagination support

---

redis-om-spring/src/main/java/com/redis/om/spring/RedisEnhancedKeyValueAdapter.java

* use pipeline to improve performance
* Reduce `instanceof` calls

use pipeline to improve performance

---

redis-om-spring/src/main/java/com/redis/om/spring/repository/query/clause/QueryClause.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/ComplexDocumentSearchTest.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/Address.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/Attribute.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/Order.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/Permit.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/PermitRepository.java

fix: prevent character escaping for full-text searches (resolves gh-69)

---

README.md

Added documentation around Gradle setup. 
resolves #76

Added gradle documentation

---

.github/wordlist.txt

Adds the word `Gradle` to the spellchecker action

ci: update wordlist for spellchecker action

---

redis-om-spring/src/main/java/com/redis/om/spring/ops/RedisModulesOperations.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/support/SimpleRedisDocumentRepository.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/support/SimpleRedisEnhancedRepository.java

Overwrting saveAll methods from SimpleRedisDocumentRepository and SimpleRedisEnhancedRepository to benefit from pipelining.

Overwriting saveAll methods of SimpleRedisRepositories

---

redis-om-spring/src/main/java/com/redis/om/spring/repository/support/RedisDocumentRepositoryFactory.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/support/RedisDocumentRepositoryFactoryBean.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/support/SimpleRedisDocumentRepository.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/support/SimpleRedisEnhancedRepository.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/BasicRedisDocumentMappingTest.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/DocumentTTLTests.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/BasicRedisHashMappingTest.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/RedisHashTTLTests.java

I added the TTL tests for the saveAll methods. The default TTL set through the annotation for the JSON repository is not working.

Implementing TTL capability to saveAll overwritten methods

---

redis-om-spring/src/main/java/com/redis/om/spring/RedisJSONKeyValueAdapter.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/support/SimpleRedisDocumentRepository.java
redis-om-spring/src/test/java/com/redis/om/spring/metamodel/MetamodelGeneratorTest.java

* Cleaned up some missing items from recent PRs

pre-release clean up

---

demos/roms-documents/pom.xml
demos/roms-hashes/pom.xml
demos/roms-permits/pom.xml
pom.xml
redis-om-spring/pom.xml
redis-om-spring/src/main/java/com/redis/om/spring/convert/MappingRedisOMConverter.java
redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamTest.java
redis-om-spring/src/test/java/com/redis/om/spring/search/stream/WrapperSearchStreamTest.java

- Refactor to address Sonar Lint warnings

refactor: sonar lint cleanup

---

redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/support/SimpleRedisDocumentRepository.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/RedisDocumentCustomFallbackKeySpaceTest.java

* use mappingContext to resolve entity prefix
* fix document repository to use derived key
* additional testcases

resolves gh-142

---

README.md
demos/roms-documents/pom.xml
demos/roms-hashes/pom.xml
demos/roms-permits/pom.xml
pom.xml
redis-om-spring/pom.xml

Removes the `SNAPSHOT` from the `0.8.0`

release: 0.8.0

---

demos/roms-documents/README.MD
demos/roms-documents/pom.xml
demos/roms-documents/src/main/java/com/redis/om/documents/controllers/EventController.java
demos/roms-documents/src/main/java/com/redis/om/documents/domain/Event.java
demos/roms-documents/src/main/java/com/redis/om/documents/repositories/EventRepository.java
demos/roms-documents/src/main/java/com/redis/om/documents/service/EventService.java
demos/roms-documents/src/main/java/com/redis/om/documents/service/impl/EventServiceImpl.java
demos/roms-documents/src/test/java/com/redis/om/documents/AbstractDocumentTest.java
demos/roms-documents/src/test/java/com/redis/om/documents/AbstractTest.java
demos/roms-documents/src/test/java/com/redis/om/documents/TestConfig.java
demos/roms-documents/src/test/java/com/redis/om/documents/controllers/EventControllerTest.java
redis-om-spring/src/main/java/com/redis/om/spring/search/stream/predicates/numeric/BetweenPredicate.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/PizzaOrder.java
redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamsAggregationsTest.java

fixed:
1. Issue 199 "invalid id for zoneoffset, invalid format..."
2. LocaDateTime to long conversion (precision)
3. Сasting primitive types without a wrapper
updated Demo-project and added tests

fix lookup with "between" LocalDateTime and Instant

---

redis-om-spring/src/main/java/com/redis/om/spring/search/stream/SearchStreamImpl.java

fixed problem with double request when aggregating via EntityStream

#209 fixed aggregation with EntityStream

---

redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RediSearchQuery.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RedisEnhancedQuery.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/BasicRedisDocumentMappingTest.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/CompanyRepository.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/BasicRedisHashMappingTest.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/fixtures/CompanyRepository.java

fix: sorting is ignored when querying from dynamic name

---

redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RediSearchQuery.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RedisEnhancedQuery.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/AggregationAnnotationTest.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/GameRepository.java

fix: correctly implements the FIRST_VALUE GROUPBY reducers

---

README.md

Sorry for being the guy that does a PR for a typo in the README.

Rename attribute @Indexable to @Indexed in README.md.

---

demos/roms-documents/pom.xml
demos/roms-hashes/pom.xml
demos/roms-permits/pom.xml
demos/roms-vss/pom.xml
pom.xml
redis-om-spring/pom.xml
redis-om-spring/src/main/java/com/redis/om/spring/RedisModulesConfiguration.java

Upgraded all upgradable dependencies before v0.8.3 release

v0.8.3 release

---

demos/roms-documents/pom.xml

There were errors when running this demo project in my IDE. The other demos don't seem to have this issue.
I just updated the annotation processors plugin as per the docs.

fix annotation processors in plugin as per the docs

---

redis-om-spring/src/main/java/com/redis/om/spring/RedisJSONKeyValueAdapter.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/RedisDocumentRepository.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/support/SimpleRedisDocumentRepository.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/OptimisticLockingTest.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/VersionedEntity.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/VersionedEntityRepository.java

For background see:
* https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongo-template.optimistic-locking
* https://docs.spring.io/spring-data/cassandra/docs/current/reference/html/#cassandra.template.optimistic-locking

feature: implements optimistic locking using Spring's @Version annotation (resolves gh-51)

---

demos/roms-documents/pom.xml
demos/roms-hashes/pom.xml
demos/roms-permits/pom.xml
demos/roms-vss/pom.xml
pom.xml
redis-om-spring/pom.xml
redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RediSearchQuery.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RedisEnhancedQuery.java
redis-om-spring/src/main/java/com/redis/om/spring/search/stream/AggregationPage.java
redis-om-spring/src/main/java/com/redis/om/spring/search/stream/AggregationStreamImpl.java
redis-om-spring/src/main/java/com/redis/om/spring/util/ObjectUtils.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/BasicRedisHashMappingTest.java

release: v0.8.5

---

demos/roms-documents/pom.xml
demos/roms-hashes/pom.xml
demos/roms-permits/pom.xml
demos/roms-vss/pom.xml
redis-om-spring/pom.xml
redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java
redis-om-spring/src/main/java/com/redis/om/spring/RedisModulesConfiguration.java
redis-om-spring/src/main/java/com/redis/om/spring/vectorize/DefaultFeatureExtractor.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/IdTests.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/Movie.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/MovieRepository.java

* dependencies: up djl version to 0.22.1
* dependencies: update spring version to 3.1.2
* fix: rename RedisTemplate Bean from redisTemplate to redisOMTemplate to prevent collisions (resolved gh-316)
* fix: numeric @Id with primitive creates TAG index field instead of NUMERIC (resolves gh-315)
* refactor: reformat to match project indentation

Bsb/release 0.8.6

---

redis-om-spring/pom.xml

* upgrade spring-test version
* upgrade guava version
* upgrade ulid version
* upgrade commons-lang version
* upgrade elementary version
* upgrade junit version

Dependencies upgrades

---

redis-om-spring/src/main/java/com/redis/om/spring/repository/support/SimpleRedisDocumentRepository.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/RedisDocumentQueryByExampleTest.java

fix - added implementation of findAll method for RedisDocumentRepository (resolves gh-344)

---

redis-om-spring/src/main/java/com/redis/om/spring/search/stream/ReturnFieldsSearchStreamImpl.java
redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamDocsTest.java
redis-om-spring/src/test/java/com/redis/om/spring/search/stream/EntityStreamHashTest.java

fix: prevent index out of bounds on nocontent empty query results

---

redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java
redis-om-spring/src/main/java/com/redis/om/spring/metamodel/indexed/TagField.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/ComplexDocumentSearchTest.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/WithNestedListOfUUIDs.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/WithNestedListOfUUIDsRepository.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/WithNestedListOfUlids.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/WithNestedListOfUlidsRepository.java

Makes UUID & ULID Indexable as TAGs

---

README.md

Small typo fix for redis stack

docs: fix redis-stack url typo

---

redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java
redis-om-spring/src/main/java/com/redis/om/spring/convert/MappingRedisOMConverter.java
redis-om-spring/src/main/java/com/redis/om/spring/id/OsTools.java
redis-om-spring/src/main/java/com/redis/om/spring/id/SecureRandom.java
redis-om-spring/src/main/java/com/redis/om/spring/id/ULIDIdentifierGenerator.java
redis-om-spring/src/main/java/com/redis/om/spring/metamodel/MetamodelGenerator.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RediSearchQuery.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RedisEnhancedQuery.java
redis-om-spring/src/main/java/com/redis/om/spring/serialization/gson/ReferenceDeserializer.java
redis-om-spring/src/main/java/com/redis/om/spring/tuple/impl/AbstractTuple.java
redis-om-spring/src/main/java/com/redis/om/spring/tuple/impl/BasicAbstractTuple.java
redis-om-spring/src/main/java/com/redis/om/spring/util/ObjectUtils.java
redis-om-spring/src/test/java/com/redis/om/spring/repository/query/QueryUtilsTest.java
redis-om-spring/src/test/java/com/redis/om/spring/repository/query/clause/QueryClauseTest.java
redis-om-spring/src/test/java/com/redis/om/spring/util/ObjectUtilsTest.java

**Implementation Smells**
_Extract Method_
Package: covert
Class: MappingRedisOMConverter.java
Method: public void write(Object source, RedisData sink)
Line number: 323
_Decompose Conditional_
Package: spring
Class: RediSearchIndexer.java
Method: private Optional<SchemaField> createIndexedFieldForIdField(Class<?> cl, List<SchemaField> fields, boolean isDocument)
Line number: 709
_Rename Method_
Package: util
Class: ObjectUtils.java
Method: public static String lcfirst(String input)
Line number: 200
**Design Smells**
_Move Method_
Package: utils, serialization.gson
Class: ObjectUtils, ReferenceDeserializer
_Extract Class_
Package: id
Class: ULIDIdentifierGenerator
_Push Down Method_
Package: tuple.impl
Class: BasicAbstractTuple, AbstractTuple

Refactor Implementation and Design smells

---

README.md
demos/roms-documents/pom.xml
demos/roms-hashes/pom.xml
demos/roms-permits/pom.xml
demos/roms-vss/pom.xml
pom.xml
redis-om-spring/pom.xml
redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java
redis-om-spring/src/main/java/com/redis/om/spring/annotations/Document.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RediSearchQuery.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/query/RedisEnhancedQuery.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/support/RedisDocumentRepositoryFactory.java
redis-om-spring/src/main/java/com/redis/om/spring/repository/support/RedisEnhancedRepositoryFactory.java
redis-om-spring/src/main/java/com/redis/om/spring/search/stream/SearchStreamImpl.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/BasicRedisDocumentMappingTest.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/CustomIndexDoc.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/fixtures/CustomIndexDocRepository.java

* feature: enable customization of the Redis Indices when declaring an Entity (resolves gh-415) 
* fix: @References fields should always be indexed as TAG fields (resolves GH-414)

0.9.1-SNAPSHOT

---

.gitignore
demos/roms-documents/pom.xml
demos/roms-hashes/pom.xml
demos/roms-permits/pom.xml
demos/roms-vss/pom.xml
redis-om-spring/pom.xml
redis-om-spring/src/main/java/com/redis/om/spring/RedisModulesConfiguration.java
redis-om-spring/src/main/java/com/redis/om/spring/RedisOMProperties.java
redis-om-spring/src/main/java/com/redis/om/spring/annotations/EmbeddingProvider.java
redis-om-spring/src/main/java/com/redis/om/spring/annotations/Vectorize.java
redis-om-spring/src/main/java/com/redis/om/spring/util/ObjectUtils.java
redis-om-spring/src/main/java/com/redis/om/spring/vectorize/DefaultFeatureExtractor.java
redis-om-spring/src/main/java/com/redis/om/spring/vectorize/FeatureExtractor.java
redis-om-spring/src/main/java/com/redis/om/spring/vectorize/NoopFeatureExtractor.java
redis-om-spring/src/test/java/com/redis/om/spring/AbstractBaseOMTest.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/RedisDocumentQueryByExampleTest.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/sentinel/BasicSentinelTest.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/vectorize/VectorizeOllamaDocumentTest.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/document/vectorize/VectorizeOpenAIDocumentTest.java
redis-om-spring/src/test/java/com/redis/om/spring/annotations/hash/serialization/SerializationTest.java
redis-om-spring/src/test/java/com/redis/om/spring/fixtures/document/model/DocWithCustomModelOpenAIEmbedding.java
redis-om-spring/src/test/java/com/redis/om/spring/fixtures/document/model/DocWithOllamaEmbedding.java
redis-om-spring/src/test/java/com/redis/om/spring/fixtures/document/model/DocWithOpenAIEmbedding.java
redis-om-spring/src/test/java/com/redis/om/spring/fixtures/document/repository/DocWithCustomModelOpenAIEmbeddingRepository.java
redis-om-spring/src/test/java/com/redis/om/spring/fixtures/document/repository/DocWithOllamaEmbeddingRepository.java
redis-om-spring/src/test/java/com/redis/om/spring/fixtures/document/repository/DocWithOpenAIEmbeddingRepository.java

Enables Redis OM Spring `@Vectorize` to use any embedding models provided by Spring AI

Spring AI Integration

---

redis-om-spring/src/main/java/com/redis/om/spring/RedisOMProperties.java
redis-om-spring/src/main/java/com/redis/om/spring/client/RedisModulesClient.java

@sazzad16 Can you double check that I am doing this correctly?

feature: report library version with Jedis' ClientSetInfoConfig

---

README.md
demos/roms-documents/pom.xml
demos/roms-hashes/pom.xml
demos/roms-permits/pom.xml
demos/roms-vss/pom.xml
pom.xml
redis-om-spring/pom.xml
redis-om-spring/src/main/java/com/redis/om/spring/RedisOMProperties.java

release: v0.9.4

---

redis-om-spring/src/main/java/com/redis/om/spring/repository/support/RedisEnhancedRepositoryFactoryBean.java

Use annotation based field autowiring in RedisEnhancedRepositoryFactoryBean

---

demos/roms-vss-movies/.gitignore
demos/roms-vss-movies/.mvn/wrapper/maven-wrapper.properties
demos/roms-vss-movies/README.md
demos/roms-vss-movies/docker-compose.yml
demos/roms-vss-movies/mvnw
demos/roms-vss-movies/mvnw.cmd
demos/roms-vss-movies/pom.xml
demos/roms-vss-movies/requests.http
demos/roms-vss-movies/src/main/java/com/redis/om/vssmovies/RomsVectorSimilaritySearchMoviesApplication.java
demos/roms-vss-movies/src/main/java/com/redis/om/vssmovies/controller/SearchController.java
demos/roms-vss-movies/src/main/java/com/redis/om/vssmovies/domain/Movie.java
demos/roms-vss-movies/src/main/java/com/redis/om/vssmovies/repository/MovieRepository.java
demos/roms-vss-movies/src/main/java/com/redis/om/vssmovies/service/MovieService.java
demos/roms-vss-movies/src/main/java/com/redis/om/vssmovies/service/SearchService.java
demos/roms-vss-movies/src/main/resources/application.properties
demos/roms-vss-movies/src/test/java/com/redis/om/vssmovies/RomsVectorSimilaritySearchMoviesApplicationTests.java
pom.xml
tests/tests.iml

@raphaeldelio said: This adds a new demo under demos/roms-vss-movies showcasing vector similarity search using Redis OM Spring. Supercedes PR #570

feat: add vector similarity search demo with movie dataset

---

redis-om-spring/src/main/java/com/redis/om/spring/client/RedisModulesClient.java
redis-om-spring/src/main/java/com/redis/om/spring/ops/RedisModulesOperations.java
redis-om-spring/src/main/java/com/redis/om/spring/ops/pds/TDigestOperations.java
redis-om-spring/src/main/java/com/redis/om/spring/ops/pds/TDigestOperationsImpl.java
tests/src/test/java/com/redis/om/spring/ops/pds/OpsForTDigestTest.java

Operations for T Digest to be followed by the annotation implementation

feat: Ops for T Digest

---

redis-om-spring/pom.xml
redis-om-spring/src/main/java/com/redis/om/spring/EntraIDConfiguration.java
redis-om-spring/src/main/java/com/redis/om/spring/RedisOMAiProperties.java
redis-om-spring/src/main/java/com/redis/om/spring/RedisOMProperties.java
redis-om-spring/src/main/java/com/redis/om/spring/client/RedisModulesClient.java
redis-om-spring/src/main/java/com/redis/om/spring/search/stream/ReturnFieldsSearchStreamImpl.java
redis-om-spring/src/main/java/com/redis/om/spring/search/stream/SearchStream.java
redis-om-spring/src/main/java/com/redis/om/spring/search/stream/SearchStreamImpl.java
redis-om-spring/src/main/java/com/redis/om/spring/search/stream/WrapperSearchStream.java
redis-om-spring/src/main/java/com/redis/om/spring/vectorize/EmbeddingModelFactory.java
redis-om-spring/src/main/resources/META-INF/spring.factories
redis-om-spring/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports

When enabling Microsoft Entra ID integration using the property `redis.om.spring.authentication.entra-id.enabled`, Redis OM will instantiate a `JedisConnectionFactory` using the EntraID authentication mechanism, instead of the traditional username/password credentials.

Connect to AMR using EntraID
